//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatisfactoryLinePlanner.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SatisfactoryLinePlanner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   assemblermk1	組立機Mk.1	15	100	assembler
        ///assemblermk2	組立機Mk.2	0	1	assembler
        ///constructormk1	製作機Mk.1	4	100	constructor
        ///constructormk2	製作機Mk.2	0	1	constructor
        ///foundrymk1	鋳造炉Mk.1	18	100	foundry
        ///foundrymk2	鋳造炉Mk.2	38	1	foundry
        ///manufacturermk1	製造機Mk.1	55	100	manufacturer
        ///manufacturermk2	製造機Mk.2	0	1	manufacturer
        ///minermk1	採掘機Mk.1	5	100	miner
        ///minermk2	採掘機Mk.2	12	200	miner
        ///minermk3	採掘機Mk.3	20	1	miner
        ///oilpump	石油汲上機	20	100	oilpump
        ///oilrefinary	石油精製機	50	100	oilrefinary
        ///smeltermk1	精錬炉Mk.1	4	100	smelter
        ///smelterm [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Facility {
            get {
                return ResourceManager.GetString("Facility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   assembler	組立機
        ///constructor	製作機
        ///foundry	鋳造炉
        ///manufacturer	製造機
        ///miner	採掘機
        ///oilpump	石油汲上機
        ///oilrefinary	石油精製機
        ///smelter	精錬炉
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FacilityType {
            get {
                return ResourceManager.GetString("FacilityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   bioburner	バイオマス発電機	20
        ///coalgenerator	石炭発電機	50
        ///fuelgenerator	燃料発電機	150
        ///geothermalgenerator	地熱発電機	200
        ///nuclearpowerplant	原子力発電機	1000
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Generator {
            get {
                return ResourceManager.GetString("Generator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ailimitter	A.I.リミッター	0
        ///bauxite	ボーキサイト	1
        ///cable	ケーブル	0
        ///cateriumingot	カテリウムインゴット	0
        ///cateriumore	カテリウム鉱石	1
        ///circuitboard	回路基盤	0
        ///coal	石炭	1
        ///computer	コンピューター	0
        ///concrete	コンクリート	0
        ///copperingot	銅インゴット	0
        ///copperore	銅鉱石	1
        ///crudeoil	石油	1
        ///encasedindustrialbeam	梱包済工業用梁(Encased Industrial Beam)	0
        ///fuel	燃料	0
        ///heavymodularframe	ヘビーモジュラーフレーム	0
        ///highspeedconnector	高速コネクター	0
        ///ironingot	鉄インゴット	0
        ///ironore	鉄鉱石	1
        ///ironplate	鉄板	0
        ///ironrod	鉄棒	0
        ///limestone	石灰石	1
        ///modularframe	モジュラーフレーム	0
        ///motor	モーター	0
        ///plastic	プラスチック	0
        ///quickwi [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MaterialData {
            get {
                return ResourceManager.GetString("MaterialData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   alternativescrew1	代替ネジ	screw	constructor	8	12
        ///defaultailimitter	A.I.リミッター	ailimitter	assembler	12	1
        ///defaultcable	ケーブル	cable	constructor	4	1
        ///defaultcateriumingot	カテリウムインゴット	cateriumingot	smelter	4	1
        ///defaultcircuitboard	回路基盤	circuitboard	assembler	12	1
        ///defaultcomputer	コンピューター	computer	manufacturer	32	1
        ///defaultconcrete	コンクリート	concrete	constructor	4	1
        ///defaultcopperingot	銅インゴット	copperingot	smelter	2	1
        ///defaultencasedindustrialbeam	梱包済工業用梁	encasedindustrialbeam	assembler	15	1
        ///defaultfuel	燃料	fuel	oilrefina [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MaterialRecipe {
            get {
                return ResourceManager.GetString("MaterialRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   defaultironingot	ironore	1
        ///defaultcopperingot	copperore	1
        ///defaultcateriumingot	cateriumore	4
        ///defaultconcrete	limestone	3
        ///defaultironplate	ironingot	2
        ///defaultironrod	ironingot	1
        ///defaultscrew	ironrod	1
        ///defaultwire	copperingot	1
        ///defaultcable	wire	2
        ///defaultsteelpipe	steelingot	1
        ///defaultsteelbeam	steelingt	3
        ///defaultsteelingot	ironore	3
        ///defaultsteelingot	coal	3
        ///defaultrubber	crudeoil	4
        ///defaultfuel	crudeoil	8
        ///defaultplastic	crudeoil	4
        ///defaultreinforcedironplate	ironplate	4
        ///defaultreinforcedironpla [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RequiredMaterialOfUnitProduction {
            get {
                return ResourceManager.GetString("RequiredMaterialOfUnitProduction", resourceCulture);
            }
        }
    }
}
